# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"
# Inserts a blank line between shell prompts
add_newline = false
format = '$username$hostname\[$directory\] $character'
right_format = """
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$golang\
$python\
$rust\
$buf\
$memory_usage\
$gcloud\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
"""

# Replace the '❯' symbol in the prompt with '➜'
[character]  # The name of the module we are configuring is 'character'
success_symbol = "[➜](bold green)"  # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
symbol = "󰏗 "
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"

[hostname]
format = "[$ssh_symbol$hostname]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "💥"
ahead = "⬆️ ${count}"
behind = "⬇️ ${count}"
diverged = "🔀"
untracked = "🫟"
stashed = "📦"
modified = "✏️"
staged = "➕"
renamed = "🔁"
deleted = "🗑️"

[golang]
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = " "

[kotlin]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[os.symbols]
Android = " "
Debian = " "
Fedora = " "
Redhat = " "
RedHatEnterprise = " "
Ubuntu = " "
Windows = "󰍲 "

[python]
symbol = " "
